default:
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    ansible_connection: 'paramiko'
    ansible_user: 'vagrant'
    ansible_ssh_pass: 'vagrant'
  hosts:
    localhost:
      ansible_host: "localhost"
  
aws:
  vars:
    ansible_ssh_user: "ec2-user"
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  hosts:
    worker-1:
        ansible_host: 3.138.154.123
    worker-2: 
        ansible_host: 18.217.55.123
    back_office:
        ansible_host: 13.58.129.253
    control:
        ansible_host: 3.137.185.10



