default:
  vars:
    ansible_connection: 'paramiko'
    ansible_user: 'vagrant'
    ansible_ssh_pass: 'vagrant'
  hosts:
    localhost:
      ansible_host: "localhost"
  
aws:
  vars:
    ansible_ssh_user: "ec2-user"
    ansible_ssh_private_key_file: "/home/vagrant/.ssh/1/back_office_generated.pem"
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  hosts:
    control:
        ansible_host: "{{ control_ec2_ip }}"
        public_hostname: ec2-3-137-185-10.us-east-2.compute.amazonaws.com
    worker-1:
        ansible_host: 3.138.154.123
        public_hostname: ec2-3-138-154-123.us-east-2.compute.amazonaws.com
    worker-2:
        ansible_host: 18.217.55.123
        public_hostname: ec2-18-217-55-123.us-east-2.compute.amazonaws.com
    back_office:
        ansible_ssh_private_key_file: "/home/vagrant/.ssh/1/back_office.pem"
        ansible_host: 13.58.129.253
        public_hostname: ec2-13-58-129-253.us-east-2.compute.amazonaws.com


