default:
  vars:
    ansible_connection: 'paramiko'
    ansible_user: 'vagrant'
    ansible_ssh_pass: 'vagrant'
  hosts:
    localhost:
      ansible_host: "localhost"
  
aws:
  vars:
    ansible_ssh_user: "ec2-user"
    ansible_ssh_private_key_file: "/home/vagrant/.ssh/id_rsa"
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  hosts:
  worker-1:
      ansible_host: ec2-18-217-120-42.us-east-2.compute.amazonaws.com
  back_office:
      ansible_host: ec2-3-133-91-226.us-east-2.compute.amazonaws.com


