---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras
    - git

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker=18.06.1 -y"

- name: Add remote "{{ ansible_user }}" user to "docker" group
  user:
    name: "{{ ansible_user }}"
    group: "docker"
    append: yes

- name: "Add temp insecure registry"
  lineinfile:
    state: present
    create: yes
    path: /etc/docker/daemon.json
    line: "'insecure-registries' : ['{{ hostvars['back_office'].ansible_host }}:5000']"
#     //{
#   "insecure-registries" : ["myregistrydomain.com:5000"]
# # }

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: reset connection
  meta: reset_connection

- name: Verify docker
  shell: bash -ilc "docker --version"

