---
- hosts: control
  become: true
  gather_facts: no
  roles:
    - dns-client
# - hosts: back_office,control
#   become: true
#   roles:
#    - aws_linux_docker

# - hosts: localhost
#   become: true
#   roles:
#    - install_docker

